# @package _global_
defaults:
  - /datamodule: dl_classify_mnist
  - /litmodule: dl_classify_mnist
  - override /hydra/launcher: local
  - _self_
hydra:
  launcher:
    cpus_per_task: 4
config:
  device: cpu
litmodule:
  config:
    num_classes: 10
  nnmodule:
    config:
      input_size: 784
      output_size: 10
      num_layers: 1
  optimizer:
    lr: 0.002
logger:
  entity: maximilienlc
trainer:
  max_epochs: 3
